accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('update-profile', views.update_student_view, name='update-profile')
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('assignment-new', views.assignment_new_view, name='assignment-new'),
    path('assignment-edit/<int:pk>', views.assignment_edit_view, name='assignment-edit'),
    path('assignment-delete/<int:pk>', views.assignment_delete_view, name='assignment-delete'),
    path('ajax/get_modules', views.get_modules_view, name='get_modules'),
]

modulverwaltungvfh/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls'))
]

# for serving statics
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Student(models.Model):
    DISCIPLINES = (
        ('MINF', 'Medieninformatik'),
        ('WINF', 'Wirtschaftsinformatik'),
    )
    userid = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, verbose_name="Benutzername")
    firstname = models.CharField(max_length=30, verbose_name="Vorname")
    lastname = models.CharField(max_length=30, verbose_name="Nachname")
    discipline = models.CharField(max_length=4, choices=DISCIPLINES, default='MINF', null=False, blank=False,
                                  verbose_name="Fachrichtung")
    startingSemester = models.CharField(max_length=7, null=False, blank=False,
                                        verbose_name="Startsemester (z.B WS17/18, SS19)")  # WS19/20, SS19

    def __str__(self):
        return '{}'.format(self.userid)

accounts/forms.py
from django import forms
from .models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('firstname', 'lastname', 'discipline', 'startingSemester')

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.db import transaction

from .forms import StudentForm
from .models import Student


def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            if user.is_superuser:
                return redirect('app:index')
            else:
                return redirect('accounts:update-profile')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            current_user = request.user
            num_results = Student.objects.filter(userid=current_user).count()
            if num_results > 0 or user.is_superuser:
                return redirect('app:index')
            else:
                return redirect('accounts:update-profile')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('app:index')


@login_required
@transaction.atomic
def update_student_view(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        current_user = request.user
        if form.is_valid():
            student = form.save(commit=False)
            student.userid = current_user
            student.save()
            return redirect('app:index')
        else:
            return HttpResponse("That's an error.")
    else:
        form = StudentForm()
    return render(request, 'accounts/update-profile.html', {'form': form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-xs-12">
            <h2>Anmelden</h2>
            <form class="form" action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "log-in" %} &nbsp;Anmelden
                    </button>
                {% endbuttons %}
            </form>
            <a href="{% url 'accounts:register' %}">Noch keinen Account?</a>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <h2>Registrieren</h2>
            <form class="form" action="{% url 'accounts:register' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %} Registrieren
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h2>Registrieren</h2>
    <form class="form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Registrieren
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

accounts/templates/accounts/update-profile.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <h2>Profil ergänzen</h2>
            <form class="form" action="{% url 'accounts:update-profile' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %} Absenden
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}