accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('update-profile', views.update_student_view, name='update-profile')
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('assignment-new', views.assignment_new_view, name='assignment-new'),
    path('assignment-edit/<int:pk>', views.assignment_edit_view, name='assignment-edit'),
    path('assignment-delete/<int:pk>', views.assignment_delete_view, name='assignment-delete'),
    path('ajax/get_modules', views.get_modules_view, name='get_modules'),
]

modulverwaltungvfh/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls'))
]

# for serving statics
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% bootstrap_messages %}

<html>
<head>
    <title>Modulverwaltung</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static '/styles/main.css' %}">
    <link rel="stylesheet" href="{% static '/styles/bootstrap-theme.min.css' %}">
</head>
<body>

<div class="container">
    <div class="page-header">
        {% if user.is_authenticated %}
            <div class="pull-right">
                <span style="padding-right: 5px">{{ user.get_username }}</span>
                <a href="{% url 'accounts:logout' %}">{% bootstrap_icon "log-out" %}</a></div>

        {% endif %}
        <h2><a href="/">Modulverwaltung</a></h2>
    </div>
    {% block content %}
    {% endblock %}
</div>
<script src="{% static '/scripts/main.js' %}"></script>
</body>
</html>