app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('assignment-new', views.assignment_new_view, name='assignment-new'),
    path('assignment-edit/<int:pk>', views.assignment_edit_view, name='assignment-edit'),
    path('assignment-delete/<int:pk>', views.assignment_delete_view, name='assignment-delete'),
    path('ajax/get_modules', views.get_modules_view, name='get_modules'),
]

modulverwaltungvfh/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls'))
]

# for serving statics
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/templates/app/assignment-new.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <h2>Modul</h2>
            <form class="form" action="{% url 'app:assignment_new' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %} Absenden
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

app/templates/app/assignment.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-xs-12">
            <h2>Modul</h2>
            <form class="form" action="{% url 'app:assignment-new' %}" method="post">
                {% csrf_token %}
            <div class="row">
                <div class="col-md-6 col-xs-12">{% bootstrap_field form.type_of_semester%}</div>
                <div class="col-md-6 col-xs-12">{% bootstrap_field form.year %}</div>
            </div>
            <div class="row">
                <div class="col-md-12">{% bootstrap_field form.module %}</div>
            </div>
            <div class="row">
                <div class="col-md-6 col-xs-12"> {% bootstrap_field form.score %}</div>
                <div class="col-md-6 col-xs-12">{% bootstrap_field form.accredited %}</div>
            </div>
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %} Absenden
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

app/templates/app/index.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-xs-12">
            <h4>Module</h4>
            <div id="modules">
                {% for semester in my_semesters %}
                    <div class="panel panel-default">
                        <div class="panel-heading clearfix">

                            <h3 class="panel-title pull-left">
                                <a href={{ "#panel-"|add:semester.name|slice:"0:11" }} data-toggle="collapse">
                                    {{ semester.name }}
                                </a>
                            </h3>

                            <a href={{ "#panel-"|add:semester.name|slice:"0:11" }}  data-toggle="collapse"
                               class="collapse-icon pull-right">
                                {% bootstrap_icon "chevron-down" %}
                            </a>
                        </div>
                        <div id={{ "panel-"|add:semester.name|slice:"0:10" }}  class="panel-body collapse
                        ">
                        <ul class="list-group">
                            {% for assignment in semester.assignments %}
                                <li class="list-group-item">
                                        <span class="badge">
                                            <a href="{% url 'app:assignment-edit' pk=assignment.pk %}"
                                               class="btn btn-link" role="button">{% bootstrap_icon "edit" %}</a>&nbsp;
                                            <a href="#" class="btn btn-link" role="button" data-toggle="modal"
                                               data-target="#confirmModal" data-modal="{{ assignment.pk }}">{% bootstrap_icon "remove-circle" %}</a>
                                        </span>
                                    {{ assignment.module.Name }} ({{ assignment.module.MID }})
                                    <small> {% if assignment.score %}{{ assignment.score }}{% endif %}
                                        {% if assignment.accredited %}anerkannt{% endif %}</small>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                    </div>
                {% endfor %}

            <p>
                <a href="{% url 'app:assignment-new' %}" class="btn btn-link" role="button">Modul hinzufügen</a>
            </p>
        </div>
    </div>
    <div class="col-md-4 col-xs-12">
        <h4>Notenspiegel</h4>
        <table class="table table-striped">
            <thead>
            <tr>
                <td>Semester</td>
                <td>Fach</td>
                <td>Note</td>
            </tr>
            </thead>
            <tbody>
            {% for entry in all_scores %}
                <tr>
                    <td>{{ entry.semester }}</td>
                    <td>{{ entry.module.Name }}</td>
                    <td>{{ entry.score }}</td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="2"><strong>Durchschnitt</strong></td>
                <td><strong>{{ median }}</strong></td>
            </tr>
            </tbody>
        </table>
        <hr/>
        <h4> Noch unbestandene Module:</h4>
        <ul class="list-unstyled">
            {% for module in unscored_modules %}
                <li class="">{{ module }}</li>
            {% endfor %}
        </ul>
        <hr/>
        <h4> Noch zu belegende Module:</h4>
        <ul class="list-unstyled">
            {% for module in available_modules %}
                {% if not module.WPF %}
                    <li class="">{{ module.Name }}</li>
                {% endif %}
            {% endfor %}
        </ul>
        <hr/>
        <h4> Noch wählbare Wahlpflichtmodule:</h4>
        <h6>noch zu belegen: {{ wpf_count }}/4</h6>
        <ul class="list-unstyled">
            {% for module in available_modules %}
                {% if module.WPF %}
                    <li class="">{{ module.Name }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModal">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Löschen</h4>
                </div>
                <div class="modal-body">
                    Soll die Modulbelegung wirklich gelöscht werden?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
                    <a id="confirmDelete" href="#" role="button" class="btn btn-primary">Löschen</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/modules.html
    <option value="">---------</option>
    {% for module in modules %}
         <option value="{{ module.pk }}">{{ module.Name }} ({{ module.MID }})</option>
    {% endfor %}

app/templates/app/prereqlist.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h3>Vorbedingung für Modul: {{ module }}</h3>
    {% for entry in prereqs %}
        <p>{{ entry.prereq.MID }}</p>
    {% endfor %}
    {% if allowed %}<p>Vorbedingungen erfüllt</p>{% else %}<p>Vorbedingungen nicht erfüllt</p>{% endif %}
{% endblock %}